### ISSUE TITLE
 pls add Windows distribution builds on PyPi

### ISSUE THREAD

**Issue by pzc163** [daily-co/daily-python#14] opened 2024-05-19 11:19 UTC
Dear Developer,

I need to deploy the ‘pipecat’ project on the Windows 11 operating system, and it requires the ‘daily-python’ project developed by your team. However, I noticed that there is no version available on PyPI that supports installation on Windows. I noticed that this project is developed using the Rust language. As I am not familiar with Rust, I am unsure how to compile this project into a .whl file that can be installed on Windows. Could your team compile a .whl package that can run on Windows 11?

**Comment by aconchillo** [comment] 2024-05-19 16:02
Hi @pzc163 . We currently don't have a version for Windows as you've find. However, we know that `daily-python` can run on Windows using WSL. Is that an option for you?

**Comment by kingsleyzhong** [comment] 2024-05-29 02:07
I would like this as well. I can use WSL but it adds a lot of unnecessary complexity to my project.

**Comment by aconchillo** [comment] 2024-06-20 19:56
Closing. Duplicate of #7

**Closed by aconchillo** 2024-06-20 19:56 UTC
