### ISSUE TITLE
Unable to install daily-python via pip for pipecat-ai integration locally

### ISSUE THREAD

**Issue by Daniel-Frei** [daily-co/daily-python#27] opened 2024-10-03 23:07 UTC
Hi,

I experienced an issue while trying to install `daily-python` as part of the `pipecat-ai` integration (with the daily extra) locally (pip install -r requirements.txt). This issue does not occur when using Docker, Here's what my `requirements.txt` looks like based on the `pipecat-ai` documentation:

```
pipecat-ai[daily,openai,silero]>=0.0.41,<0.0.42
python-dotenv>=1.0.0
aiohttp>=3.8.5
loguru>=0.5.3
```

When I attempt to install the requirements via pip:

`pip install -r requirements.txt`

I encounter the following error:

```

INFO: pip is looking at multiple versions of pipecat-ai[daily,openai,silero] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement daily-python~=0.10.1; extra == "daily" (from pipecat-ai[daily,openai,silero])
ERROR: No matching distribution found for daily-python~=0.10.1; extra == "daily"
```

It seems like the daily-python dependency cannot be found when installing pipecat-ai with the daily extra.

Additionally, I manually downloaded the daily-python v0.10.1 zip file from the daily-python releases and tried to install it locally with:

`pip install C:\Users\USERNAME\Downloads\daily-python-0.10.1.zip`

Unfortunately, I encountered the following error:

```
error: failed to get `daily-core` as a dependency of package `daily-python v0.10.1`

Caused by:
  failed to load source for dependency `daily-core`

Caused by:
  Unable to update C:\Users\USERNAME\AppData\Local\Temp\daily-core

Caused by:
  failed to read `C:\Users\USERNAME\AppData\Local\Temp\daily-core\Cargo.toml`

Caused by:
  The system cannot find the path specified. (os error 3)

Checking for Rust toolchain...
Running `maturin pep517 write-dist-info`
```

It seems like the daily-core dependency is missing or misconfigured, and the installation cannot proceed due to missing files.
System Information:

```
    Python: 3.10
    Pip: 23.0.1
    Rust: rustc 1.81.0, cargo 1.81.0
```

**Comment by aconchillo** [comment] 2024-12-19 22:51
Closing, duplicate of #7 . Unfortunately, `daily-python` is just a binary release. I see you use Windows paths and `daily-python` is not yet available on Windows.

**Closed by aconchillo** 2024-12-19 22:51 UTC
