### ISSUE TITLE
can not install daliy-python

### ISSUE THREAD

**Issue by ouyangshaoxia** [daily-co/daily-python#24] opened 2024-08-13 02:36 UTC
when I install daily-python
pip3 install daily-python

ERROR: Could not find a version that satisfies the requirement daily-python (from versions: none)
ERROR: No matching distribution found for daily-python

Can You Help Me

**Comment by kuzma2022** [comment] 2024-08-13 09:39
same error

**Comment by aconchillo** [comment] 2024-08-13 15:23
See #7

**Comment by ouyangshaoxia** [comment] 2024-08-14 01:21
os : ubuntu18.04， python==3.10,
Could not find a version that satisfies the requirement daily-python

**Comment by ouyangshaoxia** [comment] 2024-08-14 01:53
Can you provide the installation package in .whl format?

**Comment by kuzma2022** [comment] 2024-08-14 02:58
My dear I received your email, what do you want me to do for you?🥰🥰🥰

**Comment by mlxu995** [comment] 2024-08-23 08:24
same error on "CentOS Linux 7 (Core)"

**Comment by kuzma2022** [comment] 2024-08-23 10:06
My dear, I can't see your message🥹🥹🥹

**Comment by munoz-romero** [comment] 2024-08-29 12:06
I'm experiencing the same issue. Unable to install the package on:

Operating System: CentOS Linux 7 (Core)
Kernel: Linux 3.10.0-1160.102.1.el7.x86_64
Architecture: x86-64

**Comment by aconchillo** [comment] 2024-08-29 20:29
> I'm experiencing the same issue. Unable to install the package on:
> 
> Operating System: CentOS Linux 7 (Core) Kernel: Linux 3.10.0-1160.102.1.el7.x86_64 Architecture: x86-64

Yep, same problem. CentOS 7 has a very old glibc (2.17, released in 2012) and it's actually already EOL. Unfortunately, CentOS 8 also has an old glibc.

**Comment by aconchillo** [comment] 2024-09-09 17:52
Closing as duplicate of #7

**Closed by aconchillo** 2024-09-09 17:52 UTC
